[[CURRENCIES]]
code="JENGAPAY"
issuer="GA2TS3DQFII7AU3BHQVG2NPOYWV3K6BALJL2U62TKGWFMCRAWWATLNKR"
name="Jengapay Token"
desc="Hii ni token maalum kwa ajili ya huduma za Jengapay nchini Tanzania."
image="https://i.postimg.cc/x15RcS6t/jenga-pay-1024x1024.jpg"
